// Generated by build/build-logo.py. Do not edit.
//
// The mark is defined once, as three path constants, and every cut in
// src/logo/ is generated from them. Importing the paths rather than an SVG
// file is what lets a component inherit `currentColor` and re-colour a
// single strand, which no <img> can do.

export declare const WEAVE: Readonly<{
	strandA: string;
	strandB: string;
	crossing: string;
}>;

export declare const ONE_BIT: string;

export declare const WORDMARK: Readonly<{
	viewBox: string;
	path: string;
}>;

export declare const CHOP: Readonly<{
	radius: number;
	scale: number;
	offset: number;
}>;
